### ISSUE TITLE
Compiling the binary

### ISSUE THREAD

**Issue by ArtSabintsev** [obsidiansystems/ledger-app-pocket#10]
Hey all,

Going through the README, I'm trying to compile the app on my macOS machine:

here's what I get:

```
 ~/Desktop/ledger-app-pocket-0.0.4-rc1/rust-app  cargo-ledger load
warning: the cargo feature `edition2021` has been stabilized in the 1.56 release and is no longer necessary to be listed in the manifest
  See https://doc.rust-lang.org/cargo/reference/manifest.html#the-edition-field for more information about using this feature.
   Compiling cty v0.2.2
   Compiling arrayvec v0.7.2
   Compiling cfg-if v1.0.0
   Compiling zeroize v1.5.2
   Compiling kernel32-sys v0.2.2
   Compiling num-traits v0.2.14
   Compiling nanos_sdk v0.1.0 (https://github.com/obsidiansystems/ledger-nanos-sdk.git?branch=use-ambient-compiler-and-target#1d358edd)
   Compiling proc-macro2 v1.0.37
error: could not compile `cty` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `zeroize` due to 54 previous errors
error: could not compile `cfg-if` due to 3 previous errors
error: could not compile `arrayvec` due to 264 previous errors
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:163:27
stack backtrace:
   0:        0x102928f48 - std::backtrace_rs::backtrace::libunwind::trace::hce65e3f7a6c49d1b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102928f48 - std::backtrace_rs::backtrace::trace_unsynchronized::h8e403a36971945a4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102928f48 - std::sys_common::backtrace::_print_fmt::h01edb83516020417
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x102928f48 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdb141e7893323405
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x102942f64 - core::fmt::write::hed96bcfc6342aee5
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:        0x1029260cc - std::io::Write::write_fmt::h67807909d9a5a6e1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:        0x10292a670 - std::sys_common::backtrace::_print::h7267448814343cd4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x10292a670 - std::sys_common::backtrace::print::h83926e01abfb57bc
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x10292a670 - std::panicking::default_hook::{{closure}}::h23ab3d10a9c5bb0f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:        0x10292a34c - std::panicking::default_hook::hfa3eb92a01f5118c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:        0x10292ab48 - std::panicking::rust_panic_with_hook::h94fcfaabb5f8247c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:        0x10292aa04 - std::panicking::begin_panic_handler::{{closure}}::h5c2b0281f2361f0b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:586:13
  12:        0x102929424 - std::sys_common::backtrace::__rust_end_short_backtrace::h48848f94b4985ec4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x10292a794 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:        0x10294ff2c - core::panicking::panic_fmt::hfc743f4016412d36
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:        0x10294fe4c - core::panicking::panic::ha94a579c0309d35a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
  16:        0x102897358 - cargo_ledger::main::hbabde9dbff2f0d6c
  17:        0x10289a3b4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3da34336d732980c
  18:        0x102881dcc - std::rt::lang_start::{{closure}}::h2b1cb11ec0324591
  19:        0x1029220f0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h485d4c2966ec30a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  20:        0x1029220f0 - std::panicking::try::do_call::h375a887be0bea938
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  21:        0x1029220f0 - std::panicking::try::hecad40482ef3be15
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  22:        0x1029220f0 - std::panic::catch_unwind::haf1f664eb41a88eb
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  23:        0x1029220f0 - std::rt::lang_start_internal::{{closure}}::h976eba434e9ff4cf
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  24:        0x1029220f0 - std::panicking::try::do_call::h8f2501ab92e340b0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  25:        0x1029220f0 - std::panicking::try::hbeb9f8df83454d42
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  26:        0x1029220f0 - std::panic::catch_unwind::h0a9390b2202af6e9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  27:        0x1029220f0 - std::rt::lang_start_internal::hc453db0ee48af82e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  28:        0x1028979b0 - _main
  ```

**Comment by jonored** [comment]
This looks like you aren't using the version of rustc provided by the nix environment, which is currently required for the app to function at all - we require a plugin to llvm to support the peculiar memory layout from the ledger with rust's core libraries. That should currently be rust 1.53, not something higher than rust 1.56.

This particular failure looks earlier than that, but it looks like no crates are compiling, so perhaps the issue is not having the correct arm linker under the expected name?

**Comment by ArtSabintsev** [comment]
Got it - so I;m not doing this on Nix, I'm doing it on macOS. I may have misread the README. Will try again.

**Comment by jonored** [comment]
There currently isn't a documented approach to doing the build for this app other than via the nix package manager; it might work on macOS if you can get nix installed, but if not you will need to build this llvm plugin: https://github.com/obsidiansystems/ledger-platform/tree/develop/llvm-pass and force-link it into a copy of rustc like we are doing here: https://github.com/obsidiansystems/ledger-platform/blob/develop/default.nix#L53-L59

You'll also need to get the armv6m tools into the path where cargo is looking for them, which I don't have the details immediately to hand for.

It looks like nix on macOS is purportedly in a good state at this point; there were some issues when macOS made the root filesystem read-only but they appear to be ironed out. I don't have a mac right here to test on but I can probably get access to one.

**Comment by alleneubank** [comment]
FWIW I encountered a compile error today running it through Nix on Macos. @jonored 

**EDIT** I got it to work in the docker version of nix.

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/k8c4cbd63r3rpnsmx79v059g1lvcpjsd-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/share/doc/LedgerROPI -DCMAKE_INSTALL_INFODIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/include -DCMAKE_INSTALL_SBINDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/9kx1156c1azy6czs55mcngjxwbcffahq-cctools-binutils-darwin-949.0.1/bin/strip -DCMAKE_RANLIB=/nix/store/9kx1156c1azy6czs55mcngjxwbcffahq-cctools-binutils-darwin-949.0.1/bin/ranlib -DCMAKE_AR=/nix/store/9kx1156c1azy6czs55mcngjxwbcffahq-cctools-binutils-darwin-949.0.1/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/14yccva68blag472ipkvdsv2g4l7qxb2-LedgerROPI  
-- The C compiler identification is Clang 11.1.0
-- The CXX compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/9b5sdg4lcqinn8ab2hnldmjarbmggr0w-clang-wrapper-11.1.0/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/9b5sdg4lcqinn8ab2hnldmjarbmggr0w-clang-wrapper-11.1.0/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find FFI (missing: FFI_LIBRARIES HAVE_FFI_CALL) 
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /nix/store/2ccshrckfpzmjb4xc3c8dkq3mn06alid-ncurses-6.3-p20220507/lib/libtinfo.dylib  
-- Found ZLIB: /nix/store/phappqd97yd36v3vdgpksyiljqys4mwc-zlib-1.2.12/lib/libz.dylib (found version "1.2.12") 
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
[33mCMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.
[0m
-- Configuring done
-- Generating done
[33mCMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY

[0m
-- Build files have been written to: /tmp/nix-build-LedgerROPI.drv-0/source/build
cmake: enabled parallel building
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j16 -l16 SHELL=/nix/store/x7ki67lxpcqclz6q2hv0z8kyl27kdxjw-bash-5.1-p16/bin/bash
[ 50%] [32mBuilding CXX object LedgerROPI/CMakeFiles/LedgerROPI.dir/Pass.o[0m
[100%] [32m[1mLinking CXX shared module libLedgerROPI.so[0m
Undefined symbols for architecture x86_64:
  "llvm::ModulePass::assignPassManager(llvm::PMStack&, llvm::PassManagerType)", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::ModulePass::~ModulePass()", referenced from:
      (anonymous namespace)::LedgerROPI::~LedgerROPI() in Pass.o
      (anonymous namespace)::LedgerROPI::~LedgerROPI() in Pass.o
  "llvm::Instruction::setMetadata(unsigned int, llvm::MDNode*)", referenced from:
      llvm::IRBuilderBase::CreatePointerCast(llvm::Value*, llvm::Type*, llvm::Twine const&) in Pass.o
      llvm::IRBuilderBase::CreateCall(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::MDNode*) in Pass.o
  "llvm::Instruction::setFastMathFlags(llvm::FastMathFlags)", referenced from:
      llvm::IRBuilderBase::CreateCall(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::MDNode*) in Pass.o
  "llvm::Instruction::Instruction(llvm::Type*, unsigned int, llvm::Use*, unsigned int, llvm::Instruction*)", referenced from:
      llvm::CallInst::Create(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, llvm::Twine const&, llvm::Instruction*) in Pass.o
  "llvm::Instruction::~Instruction()", referenced from:
      llvm::CallInst::Create(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, llvm::Twine const&, llvm::Instruction*) in Pass.o
  "llvm::raw_ostream::write(char const*, unsigned long)", referenced from:
      llvm::detail::PassModel<llvm::Module, (anonymous namespace)::LedgerROPI_NewPM, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::printPipeline(llvm::raw_ostream&, llvm::function_ref<llvm::StringRef (llvm::StringRef)>) in Pass.o
  "llvm::FunctionType::get(llvm::Type*, llvm::ArrayRef<llvm::Type*>, bool)", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  "llvm::PassRegistry::registerPass(llvm::PassInfo const&, bool)", referenced from:
      __GLOBAL__sub_I_Pass.cpp in Pass.o
  "llvm::PassRegistry::getPassRegistry()", referenced from:
      __GLOBAL__sub_I_Pass.cpp in Pass.o
  "llvm::IRBuilderFolder::~IRBuilderFolder()", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  "llvm::SmallVectorBase<unsigned int>::mallocForGrow(unsigned long, unsigned long, unsigned long&)", referenced from:
      llvm::SmallVectorTemplateBase<std::__1::function<bool (llvm::StringRef, llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >&, llvm::ArrayRef<llvm::PassBuilder::PipelineElement>)>, false>::grow(unsigned long) in Pass.o
      llvm::SmallVectorTemplateBase<std::__1::function<void (llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >&, llvm::OptimizationLevel)>, false>::grow(unsigned long) in Pass.o
  "llvm::SmallVectorBase<unsigned int>::grow_pod(void*, unsigned long, unsigned long)", referenced from:
      llvm::IRBuilderBase::AddOrRemoveMetadataToCopy(unsigned int, llvm::MDNode*) in Pass.o
  "llvm::MetadataTracking::track(void*, llvm::Metadata&, llvm::PointerUnion<llvm::MetadataAsValue*, llvm::Metadata*>)", referenced from:
      llvm::IRBuilderBase::SetInsertPoint(llvm::Instruction*) in Pass.o
  "llvm::MetadataTracking::untrack(void*, llvm::Metadata&)", referenced from:
      llvm::IRBuilderBase::SetInsertPoint(llvm::Instruction*) in Pass.o
  "llvm::PreservedAnalyses::AllAnalysesKey", referenced from:
      llvm::detail::PassModel<llvm::Module, (anonymous namespace)::LedgerROPI_NewPM, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) in Pass.o
  "llvm::DisableABIBreakingChecks", referenced from:
      llvm::VerifyDisableABIBreakingChecks in Pass.o
  "llvm::IRBuilderDefaultInserter::~IRBuilderDefaultInserter()", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  "llvm::Pass::releaseMemory()", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::dumpPassStructure(unsigned int)", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::getAsImmutablePass()", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::getAsPMDataManager()", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::preparePassManager(llvm::PMStack&)", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::getAdjustedAnalysisPointer(void const*)", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Type::getInt32Ty(llvm::LLVMContext&)", referenced from:
      (anonymous namespace)::processModule(llvm::Module&) in Pass.o
  "llvm::Type::getInt8Ty(llvm::LLVMContext&)", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  "llvm::User::operator delete(void*)", referenced from:
      llvm::CallInst::Create(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, llvm::Twine const&, llvm::Instruction*) in Pass.o
  "llvm::User::operator new(unsigned long, unsigned int, unsigned int)", referenced from:
      llvm::CallInst::Create(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, llvm::Twine const&, llvm::Instruction*) in Pass.o
  "llvm::Module::getOrInsertGlobal(llvm::StringRef, llvm::Type*)", referenced from:
      (anonymous namespace)::processModule(llvm::Module&) in Pass.o
  "llvm::Module::getOrInsertFunction(llvm::StringRef, llvm::FunctionType*, llvm::AttributeList)", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  "llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, llvm::Twine const&)", referenced from:
      llvm::CallInst::Create(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, llvm::Twine const&, llvm::Instruction*) in Pass.o
  "llvm::CastInst::CreatePointerCast(llvm::Value*, llvm::Type*, llvm::Twine const&, llvm::Instruction*)", referenced from:
      llvm::IRBuilderBase::CreatePointerCast(llvm::Value*, llvm::Type*, llvm::Twine const&) in Pass.o
  "llvm::ModulePass::createPrinterPass(llvm::raw_ostream&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::ModulePass::getPotentialPassManagerType() const", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::AttributeList::addAttributeAtIndex(llvm::LLVMContext&, unsigned int, llvm::Attribute::AttrKind) const", referenced from:
      llvm::IRBuilderBase::CreateCall(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::MDNode*) in Pass.o
  "llvm::Pass::getPassName() const", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::verifyAnalysis() const", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::getAnalysisUsage(llvm::AnalysisUsage&) const", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Pass::print(llvm::raw_ostream&, llvm::Module const*) const", referenced from:
      vtable for (anonymous namespace)::LedgerROPI in Pass.o
  "llvm::Type::getPointerTo(unsigned int) const", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  "llvm::Value::getContext() const", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
      llvm::IRBuilderBase::CreateCall(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::MDNode*) in Pass.o
  "llvm::Function::getContext() const", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  "llvm::StringRef::find(llvm::StringRef, unsigned long) const", referenced from:
      llvm::detail::PassModel<llvm::Module, (anonymous namespace)::LedgerROPI_NewPM, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::printPipeline(llvm::raw_ostream&, llvm::function_ref<llvm::StringRef (llvm::StringRef)>) in Pass.o
      llvm::detail::PassModel<llvm::Module, (anonymous namespace)::LedgerROPI_NewPM, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::name() const in Pass.o
  "typeinfo for llvm::ModulePass", referenced from:
      typeinfo for (anonymous namespace)::LedgerROPI in Pass.o
  "vtable for llvm::ConstantFolder", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for llvm::IRBuilderDefaultInserter", referenced from:
      (anonymous namespace)::fixPointer(llvm::Instruction*, llvm::Value*, llvm::Function&, llvm::Module&) in Pass.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang-11: [0;1;31merror: [0mlinker command failed with exit code 1 (use -v to see invocation)[0m
make[2]: *** [LedgerROPI/CMakeFiles/LedgerROPI.dir/build.make:97: LedgerROPI/libLedgerROPI.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: LedgerROPI/CMakeFiles/LedgerROPI.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

This is error.log from running `nix-shell -A alamgu.rustShell`

**Comment by ApolloUnicorn** [comment]
Build instructions revised
